version: "3.5" # this is the Docker Compose specification
               # version, not the app stack version

services:

  app:
    build: .
    ports:
      - 4000:4000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: test
      DB_PASS: pass
      DB_NAME: dev
    secrets:
      - app_key
    volumes:
      - ./src:/src

  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: test
      POSTGRES_PASSWORD: pass # DONT DO THIS IN PROD -- acceptable in dev,
                              # but docker secrets should be used in prod
                              # in conjunction with docker swarm in place
                              # of docker compose

secrets:
  app_key:
    file: .secrets/app_key.txt
